# Generated by Django 5.2.5 on 2025-09-21 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='pc',
            new_name='pc_equipment',
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='labs.lab')),
            ],
        ),
    ]
