# Generated by Django 5.2.5 on 2025-09-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='labs.pc'),
        ),
    ]
