# Generated by Django 5.2.5 on 2025-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='fans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lab',
            name='lights',
            field=models.IntegerField(default=0),
        ),
    ]
