# Generated by Django 5.2.5 on 2025-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_rename_pc_software_pc_equipment_pc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='pc_equipment',
            new_name='pc',
        ),
        migrations.AddField(
            model_name='equipment',
            name='location_in_lab',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
